#!/usr/bin/env python3
# Regenerate the embedded HDR->SDR(BT.709) tone-map tables used by
# vf_sand_to_yuv420p_drm (tm=fast / tm=accurate). The tables are baked directly
# from ffmpeg's zscale+tonemap=hable chain (the chosen "zscale" tuning) so the
# filter reproduces it exactly without reimplementing zimg's math.
#
#   python3 rpi_tonemap_gen.py <path-to-ffmpeg> > rpi_tonemap_tables.h
#
# Two source-transfer variants are emitted, selected in the filter by the frame's
# color_trc: PQ/HDR10 (SMPTE2084) -> the "ff_rpi_tm_*" set, and HLG (ARIB_STD_B67)
# -> the "ff_rpi_tm_*_hlg" set. Both use the identical hable chain + grid; only the
# input transfer tag differs, so the first zscale linearizes from the correct EOTF.
#
# Assumptions baked in (see rpi-notes/pipeline/tonemap.md for making these tunable):
#   operator=hable, source peak=1000 nits (npl=100), fast chroma sat-gain=1.5,
#   3D LUT grid N=33 (limited-range 10-bit domain).
import sys, subprocess
import numpy as np

FF = sys.argv[1] if len(sys.argv) > 1 else 'ffmpeg'
ZS = "zscale=t=linear:npl=100,tonemap=hable,zscale=t=bt709:m=bt709:p=bt709:r=tv"
GAIN = 1.5
N = 33

def zscale(raw, w, h, trc='smpte2084', pix_in='yuv444p10le', pix_out='yuv444p'):
    p = subprocess.run(
        [FF, '-hide_banner', '-v', 'error', '-f', 'rawvideo', '-pix_fmt', pix_in,
         '-s', f'{w}x{h}', '-colorspace', 'bt2020nc', '-color_trc', trc,
         '-color_primaries', 'bt2020', '-color_range', 'tv', '-i', '-',
         '-vf', f'{ZS},format={pix_out}', '-f', 'rawvideo', '-'],
        input=raw, capture_output=True, check=True)
    return np.frombuffer(p.stdout, np.uint8)

def ramp444(Yv, Uv, Vv):
    W, H = 1024, 2
    Y = np.tile(Yv.astype(np.uint16), (H, 1)); U = np.tile(Uv.astype(np.uint16), (H, 1)); V = np.tile(Vv.astype(np.uint16), (H, 1))
    return Y.tobytes() + U.tobytes() + V.tobytes(), W, H

def build(trc):
    """Bake the luma1d/cb1d/cr1d/3D-LUT tables for a given source transfer."""
    x = np.arange(1024)
    # 1D luma curve (neutral chroma)
    raw, w, h = ramp444(x, np.full(1024, 512), np.full(1024, 512))
    luma1d = zscale(raw, w, h, trc)[:1024].copy()
    # 1D chroma curves at mid luma, with the fast-tier saturation gain baked in
    raw, w, h = ramp444(np.full(1024, 512), x, np.full(1024, 512))
    cb = zscale(raw, w, h, trc)[1024*h:1024*h+1024].astype(np.float32)   # U plane row 0
    raw, w, h = ramp444(np.full(1024, 512), np.full(1024, 512), x)
    cr = zscale(raw, w, h, trc)[2*1024*h:2*1024*h+1024].astype(np.float32)  # V plane row 0
    cb1d = np.clip(np.round(128 + GAIN*(cb - 128)), 0, 255).astype(np.uint8)
    cr1d = np.clip(np.round(128 + GAIN*(cr - 128)), 0, 255).astype(np.uint8)

    # 3D LUT (accurate tier): N^3 identity grid of YCbCr(2020, limited 10-bit)
    Yc = np.round(64 + np.arange(N)*(940-64)/(N-1)).astype(np.uint16)
    Cc = np.round(64 + np.arange(N)*(960-64)/(N-1)).astype(np.uint16)
    W3 = N*N; H3 = N
    Y = np.zeros((H3, W3), np.uint16); U = np.zeros((H3, W3), np.uint16); V = np.zeros((H3, W3), np.uint16)
    for iy in range(N):
        for icb in range(N):
            xs = icb*N + np.arange(N)
            Y[iy, xs] = Yc[iy]; U[iy, xs] = Cc[icb]; V[iy, xs] = Cc
    raw = Y.tobytes() + U.tobytes() + V.tobytes()
    out = zscale(raw, W3, H3, trc)
    plane = W3*H3
    Yo, Uo, Vo = out[:plane], out[plane:2*plane], out[2*plane:3*plane]
    lut = np.zeros((N, N, N, 3), np.uint8)  # [iy][icb][icr] = (Y,Cb,Cr)
    for iy in range(N):
        for icb in range(N):
            base = icb*N + np.arange(N)
            lut[iy, icb, :, 0] = Yo[iy*W3 + base]; lut[iy, icb, :, 1] = Uo[iy*W3 + base]; lut[iy, icb, :, 2] = Vo[iy*W3 + base]
    return luma1d, cb1d, cr1d, lut

def emit_1d(name, arr):
    print(f"static const uint8_t {name}[{len(arr)}] = {{")
    for i in range(0, len(arr), 16):
        print("    " + ",".join("%3d" % v for v in arr[i:i+16]) + ",")
    print("};")

def emit_3d(name, lut):
    flat = lut.reshape(-1)
    print(f"/* [iy*{N}*{N} + icb*{N} + icr]*3 + {{0:Y,1:Cb,2:Cr}} ; grid: Y in [64,940], C in [64,960] */")
    print(f"static const uint8_t {name}[{N*N*N*3}] = {{")
    for i in range(0, len(flat), 24):
        print("    " + ",".join("%3d" % v for v in flat[i:i+24]) + ",")
    print("};")

pq  = build('smpte2084')       # HDR10 / PQ
hlg = build('arib-std-b67')    # HLG

print("/* Auto-generated by rpi_tonemap_gen.py from ffmpeg zscale+tonemap=hable (1000-nit). Do not edit. */")
print("/* Two source-transfer variants: PQ (ff_rpi_tm_*) and HLG (ff_rpi_tm_*_hlg). */")
print("#ifndef AVFILTER_RPI_TONEMAP_TABLES_H")
print("#define AVFILTER_RPI_TONEMAP_TABLES_H")
print("#include <stdint.h>")
print(f"#define RPI_TM_PEAK_NITS 1000")
print(f"#define RPI_TM_LUT3D_N {N}")
emit_1d("ff_rpi_tm_luma1d", pq[0])   # 10-bit index -> 8-bit Y'
emit_1d("ff_rpi_tm_cb1d",   pq[1])   # fast separable Cb (gain baked)
emit_1d("ff_rpi_tm_cr1d",   pq[2])   # fast separable Cr (gain baked)
emit_3d("ff_rpi_tm_lut3d",  pq[3])
emit_1d("ff_rpi_tm_luma1d_hlg", hlg[0])
emit_1d("ff_rpi_tm_cb1d_hlg",   hlg[1])
emit_1d("ff_rpi_tm_cr1d_hlg",   hlg[2])
emit_3d("ff_rpi_tm_lut3d_hlg",  hlg[3])
print("#endif")
